### ISSUE TITLE
Chrome "overflowchanged" event not working anymore

### ISSUE THREAD

**Issue by muditjaju** [nathando/st-lazyload-list#1]
Hello,
Really thanks for your lazy loading list implementation. I have been using it for a while but due to a recent update in the Google Chrome the "overflowchanged" event is not working anymore and hence the images in the list when you scroll down are not visible anymore.

You can get more information here - http://trevorbrindle.com/chrome-43-broke-sencha/#comment-6274

I hope you would be able to solve this problem and also help me understand what exactly is wrong with the current code.

**Comment by nathando** [comment]
Hi, thank you for notifying me on the problem. I will need to take sometime to look at it.

**Comment by kuhamo** [comment]
same here, chrome 43 breaks it. 

thanks a lot for the cool lazy loading.

**Comment by nathando** [comment]
Added the work around for it here. https://github.com/nathando/st-lazyload-list/commit/b58897f8273addf38c59fc9fbfb469f08113d396

Basically, this update break Sencha Touch, and the 'painted' event we depends on does not work anymore. The work around is actually from [here](http://pastebin.com/PFAPfKwG) which is just force Sencha not to use 'overflowchanged' event. 

From the Sencha forum, it seems they have a nightly build for 4.0 that fixed this, but I haven't found it yet! If you have more information, just update here as well

**Comment by muditjaju** [comment]
But it does not work completely. All the list items which come to the viewport later (on scroll down) don't get their 'painted' event fired still.
Hence the showImage function is not being called ..

**Comment by nathando** [comment]
alright fixed it with this commit https://github.com/nathando/st-lazyload-list/commit/6f5172ec1f2fb34c656d0a3bb76664fb9f9676fe

Basically it was a bug from my code as well. The code was dependent on the order in which the 'painted' events were fired. When we force to not use 'overflowchanged' event but the alternative, it seems to reverse the order. 

So it's good that we found out :+1:

**Comment by muditjaju** [comment]
Hello Nathando,

Thanks a lot! Its working perfectly again!

Wanted to suggest a change:

In the function 

``` javascript
calculateScrollHeights: function(heights, len) {
        var scrollHeights = {};
        for (var i=0; i<len; i++) {
            scrollHeights[i] = (i>0 ? scrollHeights[i-1]+ heights[i-1] : 0);
        }
        return scrollHeights;
    },
```

suggested change:

``` javasctipt
scrollHeights[i] = (i>0 ? scrollHeights[i-1]+ heights[i-1] : 0);
```

What you are trying to do is set the scrollHeight equal to the lowest / bottom point of a list item, this causes the image to be loaded only when it is 'completely' inside the view, while the code I suggest makes sure that the scrollHeight is equal to the highest / top point of a list item so that even if a bit of the listitem is visible in the viewport it will lazy-load the item.

Thanks a lot! You just solved a big problem for me :)

**Comment by nathando** [comment]
oh okay, i think probably it's a side effect of reversing the order of the items. Fixed.
You are welcome!
